# This is the default config.
# If you want to make changes that persist between server reloads/restarts:
#   1. Create a new file called config.yml
#   2. Add new values for each key you want to replace (e.g., spawn-egg-chance: 0.5)
#   3. If a key doesn't exist in config.yml, the plugin will look for it in default.yml


# Chance (before bonus!) for chickens to lay spawn eggs instead of regular eggs; 1 = 100%
spawn-egg-chance: 0.5
# How far (in number of blocks) to look for named chickens when calculating bonus
named-chicken-radius: 5

# Weights for adjusting the rarity of each spawn egg; higher = more common
spawn-egg-weights:
  TROPICAL_FISH_SPAWN_EGG: 250
  COW_SPAWN_EGG: 150
  SHEEP_SPAWN_EGG: 150
  PIG_SPAWN_EGG: 150
  HORSE_SPAWN_EGG: 100
  COD_SPAWN_EGG: 100
  SALMON_SPAWN_EGG: 100
  DONKEY_SPAWN_EGG: 100
  RABBIT_SPAWN_EGG: 100
  GOAT_SPAWN_EGG: 100
  WOLF_SPAWN_EGG: 50
  BAT_SPAWN_EGG: 50
  SQUID_SPAWN_EGG: 50
  BEE_SPAWN_EGG: 50
  PARROT_SPAWN_EGG: 50
  LLAMA_SPAWN_EGG: 50
  CAT_SPAWN_EGG: 50
  FOX_SPAWN_EGG: 50
  MULE_SPAWN_EGG: 50
  TURTLE_SPAWN_EGG: 50
  PANDA_SPAWN_EGG: 50
  POLAR_BEAR_SPAWN_EGG: 50
  DOLPHIN_SPAWN_EGG: 50
  CAMEL_SPAWN_EGG: 50
  OCELOT_SPAWN_EGG: 35
  PUFFERFISH_SPAWN_EGG: 35
  TRADER_LLAMA_SPAWN_EGG: 35
  GLOW_SQUID_SPAWN_EGG: 35
  FROG_SPAWN_EGG: 35
  TADPOLE_SPAWN_EGG: 35
  ZOMBIE_SPAWN_EGG: 20
  SKELETON_SPAWN_EGG: 20
  SPIDER_SPAWN_EGG: 20
  CAVE_SPIDER_SPAWN_EGG: 20
  CREEPER_SPAWN_EGG: 20
  DROWNED_SPAWN_EGG: 20
  HUSK_SPAWN_EGG: 20
  PHANTOM_SPAWN_EGG: 20
  SILVERFISH_SPAWN_EGG: 20
  ENDERMITE_SPAWN_EGG: 20
  PILLAGER_SPAWN_EGG: 20
  ALLAY_SPAWN_EGG: 20
  SNOW_GOLEM_SPAWN_EGG: 20
  STRIDER_SPAWN_EGG: 15
  SLIME_SPAWN_EGG: 15
  WANDERING_TRADER_SPAWN_EGG: 15
  AXOLOTL_SPAWN_EGG: 15
  IRON_GOLEM_SPAWN_EGG: 15
  ZOMBIFIED_PIGLIN_SPAWN_EGG: 10
  VEX_SPAWN_EGG: 10
  WITCH_SPAWN_EGG: 10
  VINDICATOR_SPAWN_EGG: 10
  STRAY_SPAWN_EGG: 10
  GUARDIAN_SPAWN_EGG: 10
  ENDERMAN_SPAWN_EGG: 10
  PIGLIN_SPAWN_EGG: 10
  PIGLIN_BRUTE_SPAWN_EGG: 10
  ZOGLIN_SPAWN_EGG: 10
  HOGLIN_SPAWN_EGG: 10
  MAGMA_CUBE_SPAWN_EGG: 10
  BLAZE_SPAWN_EGG: 7
  RAVAGER_SPAWN_EGG: 7
  WITHER_SKELETON_SPAWN_EGG: 5
  SHULKER_SPAWN_EGG: 5
  EVOKER_SPAWN_EGG: 5
  SKELETON_HORSE_SPAWN_EGG: 5
  VILLAGER_SPAWN_EGG: 5
  ZOMBIE_VILLAGER_SPAWN_EGG: 5
  MOOSHROOM_SPAWN_EGG: 3
  ELDER_GUARDIAN_SPAWN_EGG: 3
  GHAST_SPAWN_EGG: 3
  SNIFFER_SPAWN_EGG: 3
  WARDEN_SPAWN_EGG: 2
  CHICKEN_SPAWN_EGG: 1
  ZOMBIE_HORSE_SPAWN_EGG: 1
  WITHER_SPAWN_EGG: 0
  ENDER_DRAGON_SPAWN_EGG: 0
